-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 15:18:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gepw_lifecycle_tool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gepw_lifecycle_tool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gepw_lifecycle_tool` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `gepw_lifecycle_tool` ;

-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`roles` (
  `role_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `can_admin` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `can_view_all_parts` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `can_view_all_reports` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `can_edit_report` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_id`),
  INDEX `IDX_role_name` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`uom_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`uom_categories` (
  `uom_categories_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`uom_categories_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`uom_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`uom_values` (
  `uom_value_id` VARCHAR(40) NOT NULL,
  `uom_category_id` VARCHAR(40) NOT NULL,
  `uom_description` VARCHAR(200) NOT NULL,
  `uom_abbreviation` VARCHAR(60) NOT NULL,
  `base_uom` TINYINT(1) UNSIGNED NOT NULL,
  `uom_multiplier` FLOAT UNSIGNED NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uom_value_id`),
  INDEX `FK_uom_values_uom_category_idx` (`uom_category_id` ASC),
  CONSTRAINT `FK_uom_values_uom_category`
    FOREIGN KEY (`uom_category_id`)
    REFERENCES `gepw_lifecycle_tool`.`uom_categories` (`uom_categories_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`currencies` (
  `currency_id` VARCHAR(40) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `short_name` VARCHAR(3) NOT NULL,
  `symbol` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`currency_id`),
  INDEX `IDX_currency_short_name` (`short_name` ASC),
  INDEX `IDX_currency_full_name` (`full_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`users` (
  `user_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(80) NULL,
  `gesso` VARCHAR(100) NOT NULL,
  `role_id` VARCHAR(40) NOT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  `default_uom_gas_id` VARCHAR(40) NULL DEFAULT NULL,
  `default_uom_energy_id` VARCHAR(40) NULL DEFAULT NULL,
  `default_uom_volume_id` VARCHAR(40) NULL DEFAULT NULL,
  `default_uom_power_id` VARCHAR(40) NULL DEFAULT NULL,
  `default_uom_weight_id` VARCHAR(40) NULL DEFAULT NULL,
  `currency_id` VARCHAR(40) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `last_login` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  INDEX `IDX_user_gesso` (`gesso` ASC),
  INDEX `FK_user_role_idx` (`role_id` ASC),
  INDEX `IDX_user_name` (`name` ASC),
  INDEX `FK_users_uom_values_idx` (`default_uom_gas_id` ASC),
  INDEX `FK_users_currency_idx` (`currency_id` ASC),
  INDEX `FK_users_uom_energy_idx` (`default_uom_energy_id` ASC),
  INDEX `FK_users_uom_power_idx` (`default_uom_power_id` ASC),
  INDEX `FK_users_uom_volume_idx` (`default_uom_volume_id` ASC),
  INDEX `FK_users_uom_wieght_idx` (`default_uom_weight_id` ASC),
  CONSTRAINT `FK_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `gepw_lifecycle_tool`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_users_uom_gas`
    FOREIGN KEY (`default_uom_gas_id`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_users_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `gepw_lifecycle_tool`.`currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_users_uom_energy`
    FOREIGN KEY (`default_uom_energy_id`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_users_uom_power`
    FOREIGN KEY (`default_uom_power_id`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_users_uom_volume`
    FOREIGN KEY (`default_uom_volume_id`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_users_uom_wieght`
    FOREIGN KEY (`default_uom_weight_id`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`companies` (
  `company_id` VARCHAR(40) NOT NULL,
  `creator_user_id` VARCHAR(40) NULL,
  `name` VARCHAR(60) NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_id`),
  INDEX `IDX_companies_name` (`name` ASC),
  INDEX `FK_company_creator_user_idx` (`creator_user_id` ASC),
  CONSTRAINT `FK_company_creator_user`
    FOREIGN KEY (`creator_user_id`)
    REFERENCES `gepw_lifecycle_tool`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`contacts` (
  `contact_id` VARCHAR(40) NOT NULL,
  `company_id` VARCHAR(40) NULL,
  `creator_user_id` VARCHAR(40) NULL,
  `name` VARCHAR(100) NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`contact_id`),
  INDEX `FK_contact_company` (`company_id` ASC),
  INDEX `IDX_company_name` (`name` ASC),
  INDEX `FK_contact_creator_user_idx` (`creator_user_id` ASC),
  CONSTRAINT `FK_contact_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `gepw_lifecycle_tool`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_contact_creator_user`
    FOREIGN KEY (`creator_user_id`)
    REFERENCES `gepw_lifecycle_tool`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`fuels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`fuels` (
  `fuel_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `alt_warning` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`fuel_id`),
  INDEX `IDX_fuel_name` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`engines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`engines` (
  `engine_id` VARCHAR(40) NOT NULL,
  `model` VARCHAR(30) NOT NULL,
  `image_url` VARCHAR(300) NULL,
  `model_status` CHAR(1) NULL,
  `oil_consumption_rate` FLOAT NULL,
  `lube_oil_capacity` FLOAT NULL COMMENT 'ENTERED IN GALLONS',
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`engine_id`),
  INDEX `IDX_engine_model` (`model` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`oil_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`oil_type` (
  `oil_type_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`oil_type_id`),
  INDEX `IDX_lube_oil_oil_type` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`engines_speeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`engines_speeds` (
  `engines_speeds_id` VARCHAR(40) NOT NULL,
  `engine_id` VARCHAR(40) NOT NULL,
  `rpm` SMALLINT(5) UNSIGNED NOT NULL,
  `max_bhp` SMALLINT(5) UNSIGNED NOT NULL,
  `btu_hp_hp_formula` VARCHAR(100) NULL,
  `bottom_end_overhaul_hours` MEDIUMINT(8) UNSIGNED NOT NULL,
  `top_to_bottom_ratio` TINYINT(2) UNSIGNED NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`engines_speeds_id`),
  INDEX `FK_engine_speeds_engine_idx` (`engine_id` ASC),
  UNIQUE INDEX `UNQ_engines_speeds_engine_rpm` (`engine_id` ASC, `rpm` ASC),
  CONSTRAINT `FK_engine_speeds_engine`
    FOREIGN KEY (`engine_id`)
    REFERENCES `gepw_lifecycle_tool`.`engines` (`engine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`reports` (
  `report_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `contact_id` VARCHAR(40) NOT NULL,
  `creator_user_id` VARCHAR(40) NOT NULL,
  `inflation` TINYINT(3) UNSIGNED NULL,
  `currency_id` VARCHAR(40) NOT NULL,
  `engine_id` VARCHAR(40) NOT NULL,
  `engine_speed_id` VARCHAR(40) NULL,
  `site_load` SMALLINT(4) NULL,
  `site_load_uom` VARCHAR(40) NULL,
  `date_of_commissioning` DATETIME NULL,
  `annual_operating_hours` SMALLINT(4) UNSIGNED NULL,
  `engine_count` SMALLINT(5) UNSIGNED NULL,
  `use_parts_list_price_discount` TINYINT(1) NULL DEFAULT 0,
  `parts_list_price_discount` TINYINT(3) NOT NULL,
  `include_fuel` TINYINT(1) NULL,
  `fuel_id` VARCHAR(40) NOT NULL,
  `fuel_cost` FLOAT UNSIGNED NULL,
  `fuel_uom` VARCHAR(40) NULL,
  `include_lubrication` TINYINT(1) UNSIGNED NULL,
  `oil_type_id` VARCHAR(40) NOT NULL,
  `oil_consumption` FLOAT UNSIGNED NULL,
  `oil_consumption_uom` VARCHAR(40) NULL,
  `oil_cost` FLOAT UNSIGNED NULL,
  `oil_cost_uom` VARCHAR(40) NULL,
  `include_labor` TINYINT(1) UNSIGNED NULL,
  `labor_rate` FLOAT UNSIGNED NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `show_data_by_years` TINYINT(1) NULL,
  PRIMARY KEY (`report_id`),
  INDEX `FK_report_contact_idx` (`contact_id` ASC),
  INDEX `FK_report_user_idx` (`creator_user_id` ASC),
  INDEX `FK_report_fuel_idx` (`fuel_id` ASC),
  INDEX `FK_report_engine_idx` (`engine_id` ASC),
  INDEX `FK_report_lube_oil_idx` (`oil_type_id` ASC),
  INDEX `IDX_report_name` (`name` ASC),
  INDEX `FK_report_uom_idx` (`fuel_uom` ASC),
  INDEX `FK_report_currency_idx` (`currency_id` ASC),
  INDEX `FK_report_site_load_uom_idx` (`site_load_uom` ASC),
  INDEX `FK_report_oil_consumption_uom_idx` (`oil_consumption_uom` ASC),
  INDEX `FK_report_oil_cost_uom_idx` (`oil_cost_uom` ASC),
  INDEX `FK_report_engine_speed_idx` (`engine_speed_id` ASC),
  CONSTRAINT `FK_report_contact`
    FOREIGN KEY (`contact_id`)
    REFERENCES `gepw_lifecycle_tool`.`contacts` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_user`
    FOREIGN KEY (`creator_user_id`)
    REFERENCES `gepw_lifecycle_tool`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_fuel`
    FOREIGN KEY (`fuel_id`)
    REFERENCES `gepw_lifecycle_tool`.`fuels` (`fuel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_engine`
    FOREIGN KEY (`engine_id`)
    REFERENCES `gepw_lifecycle_tool`.`engines` (`engine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_lube_oil`
    FOREIGN KEY (`oil_type_id`)
    REFERENCES `gepw_lifecycle_tool`.`oil_type` (`oil_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_fuel_uom`
    FOREIGN KEY (`fuel_uom`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `gepw_lifecycle_tool`.`currencies` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_engine_speed`
    FOREIGN KEY (`engine_speed_id`)
    REFERENCES `gepw_lifecycle_tool`.`engines_speeds` (`engines_speeds_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_site_load_uom`
    FOREIGN KEY (`site_load_uom`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_oil_consumption_uom`
    FOREIGN KEY (`oil_consumption_uom`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_oil_cost_uom`
    FOREIGN KEY (`oil_cost_uom`)
    REFERENCES `gepw_lifecycle_tool`.`uom_values` (`uom_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`parts_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`parts_type` (
  `parts_type_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`parts_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`parts_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`parts_categories` (
  `parts_category_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`parts_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`parts` (
  `part_id` VARCHAR(40) NOT NULL,
  `currency_id` VARCHAR(40) NULL DEFAULT NULL,
  `user_id` VARCHAR(40) NULL DEFAULT NULL,
  `part_number` VARCHAR(40) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `list_price` FLOAT UNSIGNED NOT NULL,
  `part_category_id` VARCHAR(36) NOT NULL,
  `part_type_id` VARCHAR(36) NOT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`part_id`),
  INDEX `FK_parts_user_id_idx` (`user_id` ASC),
  INDEX `FK_parts_currency_idx` (`currency_id` ASC),
  INDEX `FK_parts_parts_type_idx` (`part_type_id` ASC),
  INDEX `FK_parts_part_categories_idx` (`part_category_id` ASC),
  CONSTRAINT `FK_parts_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `gepw_lifecycle_tool`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_parts_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `gepw_lifecycle_tool`.`currencies` (`currency_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_parts_parts_type`
    FOREIGN KEY (`part_type_id`)
    REFERENCES `gepw_lifecycle_tool`.`parts_type` (`parts_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_parts_part_categories`
    FOREIGN KEY (`part_category_id`)
    REFERENCES `gepw_lifecycle_tool`.`parts_categories` (`parts_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`users_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`users_settings` (
  `user_settings_id` VARCHAR(40) NOT NULL,
  `user_id` VARCHAR(40) NOT NULL,
  `setting_key` VARCHAR(50) NOT NULL,
  `setting_value` VARCHAR(500) NULL,
  PRIMARY KEY (`user_settings_id`),
  INDEX `FK_user_setting_user_id_idx` (`user_id` ASC),
  INDEX `IDX_user_setting_user_id_settings_key` (`user_id` ASC, `setting_key` ASC),
  INDEX `IDX_user_setting_user_id` (`user_id` ASC),
  CONSTRAINT `FK_user_setting_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `gepw_lifecycle_tool`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`interval_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`interval_types` (
  `interval_types_id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`interval_types_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`intervals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`intervals` (
  `interval_id` VARCHAR(40) NOT NULL,
  `engine_id` VARCHAR(40) NOT NULL,
  `interval_type_id` VARCHAR(40) NOT NULL,
  `repeat` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `labor_hours` SMALLINT(5) UNSIGNED NULL DEFAULT 0,
  `occurrence_hour` MEDIUMINT(8) UNSIGNED NOT NULL,
  `travel_expense` FLOAT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`interval_id`),
  INDEX `FK_interval_engine_idx` (`engine_id` ASC),
  INDEX `FK_interval_interval_type_idx` (`interval_type_id` ASC),
  CONSTRAINT `FK_interval_engine`
    FOREIGN KEY (`engine_id`)
    REFERENCES `gepw_lifecycle_tool`.`engines` (`engine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_interval_interval_type`
    FOREIGN KEY (`interval_type_id`)
    REFERENCES `gepw_lifecycle_tool`.`interval_types` (`interval_types_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`reports_intervals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`reports_intervals` (
  `report_interval_id` VARCHAR(40) NOT NULL,
  `interval_id` VARCHAR(40) NOT NULL,
  `report_id` VARCHAR(40) NOT NULL,
  `labor_hours` SMALLINT(5) UNSIGNED NULL DEFAULT 0,
  `occurrence_hour` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0,
  `travel_expenses` FLOAT NULL,
  `repeat` TINYINT(1) UNSIGNED NOT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT 1,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`report_interval_id`),
  INDEX `FK_report_interval_report_idx` (`report_id` ASC),
  INDEX `FK_report_interval_interval_idx` (`interval_id` ASC),
  CONSTRAINT `FK_report_interval_report`
    FOREIGN KEY (`report_id`)
    REFERENCES `gepw_lifecycle_tool`.`reports` (`report_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_interval_interval`
    FOREIGN KEY (`interval_id`)
    REFERENCES `gepw_lifecycle_tool`.`intervals` (`interval_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`intervals_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`intervals_parts` (
  `interval_parts_id` INT NOT NULL,
  `interval_id` VARCHAR(40) NOT NULL,
  `part_id` VARCHAR(40) NOT NULL,
  `count` INT UNSIGNED NULL DEFAULT 1,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`interval_parts_id`),
  INDEX `FK_interval_part_part_idx` (`part_id` ASC),
  INDEX `FK_interval_part_interval_idx` (`interval_id` ASC),
  CONSTRAINT `FK_interval_part_part`
    FOREIGN KEY (`part_id`)
    REFERENCES `gepw_lifecycle_tool`.`parts` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_interval_part_interval`
    FOREIGN KEY (`interval_id`)
    REFERENCES `gepw_lifecycle_tool`.`intervals` (`interval_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`reports_intervals_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`reports_intervals_parts` (
  `reports_intervals_parts_id` VARCHAR(40) NOT NULL,
  `report_interval_id` VARCHAR(40) NULL,
  `part_id` VARCHAR(40) NULL,
  `quantity` MEDIUMINT(8) UNSIGNED NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`reports_intervals_parts_id`),
  INDEX `FK_reports_intervals_parts_idx` (`report_interval_id` ASC),
  INDEX `FK_report_interval_part_part_idx` (`part_id` ASC),
  CONSTRAINT `FK_report_interval_part_report_interval`
    FOREIGN KEY (`report_interval_id`)
    REFERENCES `gepw_lifecycle_tool`.`reports_intervals` (`report_interval_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_report_interval_part_part`
    FOREIGN KEY (`part_id`)
    REFERENCES `gepw_lifecycle_tool`.`parts` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`shared_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`shared_reports` (
  `shared_reports_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(40) NOT NULL,
  `report_id` VARCHAR(40) NOT NULL,
  `addresses_to` VARCHAR(1000) NOT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`shared_reports_id`),
  INDEX `FK_shared_reports_user_idx` (`user_id` ASC),
  INDEX `FK_shared_reports_report_idx` (`report_id` ASC),
  CONSTRAINT `FK_shared_reports_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `gepw_lifecycle_tool`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_shared_reports_report`
    FOREIGN KEY (`report_id`)
    REFERENCES `gepw_lifecycle_tool`.`reports` (`report_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gepw_lifecycle_tool`.`currency_exchange_rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gepw_lifecycle_tool`.`currency_exchange_rates` (
  `from` CHAR(3) NOT NULL,
  `to` CHAR(3) NOT NULL,
  `rate` FLOAT UNSIGNED NOT NULL,
  `rate_as_of` DATETIME NOT NULL,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`from`, `to`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
